# Generated by Django 2.0.5 on 2018-06-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='doe',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemassignment',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
