# Generated by Django 2.0.5 on 2018-06-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20180602_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemassignment',
            name='item_id',
        ),
        migrations.AddField(
            model_name='itemassignment',
            name='item_id',
            field=models.ManyToManyField(to='db.Items'),
        ),
    ]
