# Generated by Django 2.0.5 on 2018-06-03 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20180603_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemassignment',
            name='item_id',
        ),
        migrations.AddField(
            model_name='itemassignment',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.Items'),
        ),
    ]
